openapi: 3.0.3
info:
  title: "go-scaffold API"
  version: "1.0.0"
  description: "go-scaffold API"
# servers:
#   - url: "/"
#     description: "noversion"
#     - url: "/v1"
#     description: "v1"
paths:
  /health:
    get:
      tags: ["System"]
      summary: "Health check"
      description: "Health check"
      responses:
        '200':
          description: "OK"
  /v1/user:
    post:
      tags: ["User"]
      summary: "Create user"
      description: "Create user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPost"
      responses:
        '200':
          description: "OK"

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "{{.AuthorizationUrl}}"
          tokenUrl: "{{.TokenUrl}}"
          # scopes:
          #   read: "Read access"
          #   write: "Write access"
    X-IAM-AUTH-SIGNATURE:
      type: apiKey
      in: header
      name: X-IAM-AUTH-SIGNATURE
    X-IAM-API-KEY:
      type: apiKey
      in: header
      name: X-IAM-API-KEY
  schemas:
    UserPost:
      type: object
      properties:
        name:
          type: string
          description: "User name"
        email:
          type: string
          description: "User email"
        age:
          type: integer
          description: "User age"
        password:
          type: string
          description: "User password"
      required:
        - name
        - age
    
    